"""Third migration

Revision ID: 111c6257c8cf
Revises: a4f6957e01ed
Create Date: 2024-09-02 13:14:30.388027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111c6257c8cf'
down_revision: Union[str, None] = 'a4f6957e01ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('our_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_our_work_id'), 'our_work', ['id'], unique=False)
    op.create_table('result_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_result_category_id'), 'result_category', ['id'], unique=False)
    op.create_table('our_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['result_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_our_result_id'), 'our_result', ['id'], unique=False)
    op.create_table('our_work_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('our_work', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['our_work'], ['our_work.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_our_work_detail_id'), 'our_work_detail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_our_work_detail_id'), table_name='our_work_detail')
    op.drop_table('our_work_detail')
    op.drop_index(op.f('ix_our_result_id'), table_name='our_result')
    op.drop_table('our_result')
    op.drop_index(op.f('ix_result_category_id'), table_name='result_category')
    op.drop_table('result_category')
    op.drop_index(op.f('ix_our_work_id'), table_name='our_work')
    op.drop_table('our_work')
    # ### end Alembic commands ###
