"""Feedback image

Revision ID: 47201a4d021b
Revises: 157e2ee1601c
Create Date: 2024-09-04 18:41:36.953660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision: str = '47201a4d021b'
down_revision: Union[str, None] = '157e2ee1601c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'image',
               existing_type=sa.TEXT(),
               type_=ImageType(fastapi_storages.FileSystemStorage(path='tmp/')),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'image',
               existing_type=ImageType(fastapi_storages.FileSystemStorage(path='tmp/')),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
