"""Portfolio image

Revision ID: 566d7f77ff6d
Revises: ac3817cdcb3f
Create Date: 2024-09-04 19:06:37.109379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages import FileSystemStorage
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision: str = '566d7f77ff6d'
down_revision: Union[str, None] = 'ac3817cdcb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('our_result', 'image',
               existing_type=sa.TEXT(),
               type_=ImageType(FileSystemStorage(path='tmp/')),
               existing_nullable=True)
    op.alter_column('our_work', 'image',
               existing_type=sa.TEXT(),
               type_=ImageType(FileSystemStorage(path='tmp/')),
               existing_nullable=True)
    op.alter_column('our_work_detail', 'image',
               existing_type=sa.TEXT(),
               type_=ImageType(FileSystemStorage(path='tmp/')),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('our_work_detail', 'image',
               existing_type=ImageType(FileSystemStorage(path='tmp/')),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('our_work', 'image',
               existing_type=ImageType(FileSystemStorage(path='tmp/')),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('our_result', 'image',
               existing_type=ImageType(FileSystemStorage(path='tmp/')),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
