"""Admin

Revision ID: 61b682004859
Revises: 111c6257c8cf
Create Date: 2024-09-03 15:13:13.225971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision: str = '61b682004859'
down_revision: Union[str, None] = '111c6257c8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banner', 'image',
               existing_type=sa.TEXT(),
               type_=ImageType(storage=fastapi_storages.FileSystemStorage(path="/tmp")),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banner', 'image',
               existing_type=ImageType(storage=fastapi_storages.FileSystemStorage(path="/tmp")),
               type_=sa.TEXT(),
               existing_nullable=True)