"""Second migration

Revision ID: 88f302846c3e
Revises: 18cd7cc6f7d9
Create Date: 2024-09-01 18:54:22.826351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f302846c3e'
down_revision: Union[str, None] = '18cd7cc6f7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contactus_id'), 'contactus', ['id'], unique=False)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_id'), 'faq', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('job', sa.String(length=70), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('our_team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_our_team_member_id'), 'our_team_member', ['id'], unique=False)
    op.create_table('socila_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facebook_url', sa.Text(), nullable=True),
    sa.Column('twitter_url', sa.Text(), nullable=True),
    sa.Column('vimeo_url', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socila_media_id'), 'socila_media', ['id'], unique=False)
    op.create_table('sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsor_id'), 'sponsor', ['id'], unique=False)
    op.create_table('why_we',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_why_we_id'), 'why_we', ['id'], unique=False)
    op.alter_column('banner', 'desc',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_banner_id'), 'banner', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banner_id'), table_name='banner')
    op.alter_column('banner', 'desc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_why_we_id'), table_name='why_we')
    op.drop_table('why_we')
    op.drop_index(op.f('ix_sponsor_id'), table_name='sponsor')
    op.drop_table('sponsor')
    op.drop_index(op.f('ix_socila_media_id'), table_name='socila_media')
    op.drop_table('socila_media')
    op.drop_index(op.f('ix_our_team_member_id'), table_name='our_team_member')
    op.drop_table('our_team_member')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_faq_id'), table_name='faq')
    op.drop_table('faq')
    op.drop_index(op.f('ix_contactus_id'), table_name='contactus')
    op.drop_table('contactus')
    # ### end Alembic commands ###
