"""Second migration

Revision ID: a4f6957e01ed
Revises: 88f302846c3e
Create Date: 2024-09-01 19:44:35.203935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f6957e01ed'
down_revision: Union[str, None] = '88f302846c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('banner', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('banner', sa.Column('email', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'email')
    op.drop_column('banner', 'image')
    op.drop_column('banner', 'phone')
    # ### end Alembic commands ###
