"""Company image

Revision ID: ac3817cdcb3f
Revises: 47201a4d021b
Create Date: 2024-09-04 19:02:09.175418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages import FileSystemStorage
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision: str = 'ac3817cdcb3f'
down_revision: Union[str, None] = '47201a4d021b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('our_team_member', 'image',
               existing_type=sa.TEXT(),
               type_=ImageType(FileSystemStorage(path='tmp/')),
               existing_nullable=True)
    op.alter_column('sponsor', 'image',
               existing_type=sa.TEXT(),
               type_=ImageType(FileSystemStorage(path='tmp/')),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sponsor', 'image',
               existing_type=ImageType(FileSystemStorage(path='tmp/')),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('our_team_member', 'image',
               existing_type=ImageType(FileSystemStorage(path='tmp/')),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
