"""Last migration

Revision ID: aeb770d04399
Revises: 
Create Date: 2024-09-18 21:25:20.219685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages import FileSystemStorage
from fastapi_storages.integrations.sqlalchemy import ImageType



# revision identifiers, used by Alembic.
revision: str = 'aeb770d04399'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('portfolio_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image', ImageType(storage=FileSystemStorage(path='tmp/')), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['portfolio_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_and_portfolio',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_item.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['portfolio_tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'portfolio_id')
    )
    op.alter_column('banner', 'desc',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banner', 'desc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('tag_and_portfolio')
    op.drop_table('portfolio_item')
    op.drop_table('portfolio_tag')
    op.drop_table('portfolio_category')
    # ### end Alembic commands ###
