"""Last migration

Revision ID: e5895a2b9c4e
Revises: aeb770d04399
Create Date: 2024-09-19 18:40:38.554942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5895a2b9c4e'
down_revision: Union[str, None] = 'aeb770d04399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faq', 'order')
    # ### end Alembic commands ###
