"""empty message

Revision ID: 383d1465dcde
Revises: 4ea1857f58f1
Create Date: 2024-09-30 19:27:54.508803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383d1465dcde'
down_revision: Union[str, None] = '4ea1857f58f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('our_services', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('our_team', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('portfolio_item', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('social_medias', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sponsors', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('why_we_us', 'bg_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('why_we_us', 'bg_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sponsors', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('social_medias', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('portfolio_item', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('our_team', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('our_services', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
