"""empty message

Revision ID: 4ea1857f58f1
Revises: 
Create Date: 2024-09-27 19:29:45.016887

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from fastapi_storages.integrations.sqlalchemy import ImageType
from fastapi_storages import FileSystemStorage

# revision identifiers, used by Alembic.
revision: str = '4ea1857f58f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('page_type', sa.Enum('MAIN', 'ABOUT', 'PORTFOLIO', name='pagetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('faq_type', sa.Enum('GENERAL', 'COMPANY', name='faqtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column(storage=FileSystemStorage(path="/tmp"), nullable=True),
    sa.Column('feedback_text', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('our_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('image', ImageType(storage=FileSystemStorage(path="/tmp")), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('our_team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', ImageType(storage=FileSystemStorage(path="/tmp")), nullable=True),
    sa.Column('experience', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('portfolio_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('social_medias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column(storage=FileSystemStorage(path="/tmp"), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column(storage=FileSystemStorage(path="/tmp"), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('why_we_us',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('bg_image', storage=FileSystemStorage(path="/tmp"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_with_us',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('service_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_type'], ['our_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('our_service_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('additional_info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['our_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image', ImageType(storage=FileSystemStorage(path="/tmp")), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['portfolio_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_and_portfolio',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_item.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['portfolio_tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'portfolio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_and_portfolio')
    op.drop_table('portfolio_item')
    op.drop_table('our_service_info')
    op.drop_table('feature')
    op.drop_table('contact_with_us')
    op.drop_table('why_we_us')
    op.drop_table('sponsors')
    op.drop_table('social_medias')
    op.drop_table('portfolio_tag')
    op.drop_table('portfolio_category')
    op.drop_table('plan')
    op.drop_table('our_team')
    op.drop_table('our_services')
    op.drop_table('feedbacks')
    op.drop_table('faq')
    op.drop_table('config')
    op.drop_table('banner')
    # ### end Alembic commands ###
